### PR TITLE
code challenge

### PR DESCRIPTION
**Pull request by ludoplex**
My assignment.

### CODE REVIEW

**Comment by jaywon** [comment]
Hi. I can't seem to match your handle with your name. Can you please tell me who you are :D

**Comment by ludoplex** [comment]
Vincent L. Anderson

**Comment by ludoplex** [comment]
This is the completed version of the code challenge I was given.

**Comment by ludoplex** [comment]
Hi devleague/gee-mail,

I'd like to add you to my professional network on LinkedIn.

- Vincent

Confirm that you know Vincent: https://www.linkedin.com/e/v2?e=0-in8rvoar-us&t=ssuw&tracking=eml-guest-invite-cta&ek=invite_guest&sharedKey=i4Oc8zGP&invitationId=6128513444078514177








You received an invitation to connect. LinkedIn will use your email address to make suggestions to our members in features like People You May Know. Unsubscribe here: https://www.linkedin.com/e/v2?e=0-in8rvoar-us&t=lun&midToken=AQFmrFVhGEd36Q&ek=invite_guest&loid=AQF7W4HQmD3r9QAAAVQzaqjedYLBAgr5eiAZsdJTySU79JtO8hRnVOaPstTv1K69vbiv_cRU6V7wvOpfn59llkFszevZNr_HcxfPZEQzS4pH-TMCZBgPP74-yBVZotZ0HQhMN_kKCg0YPicZgxmhadKRHwD13bl2RgZuwXDhUelpnZJ28Rn81BHLXPs3Ti3ojwxb&eid=0-in8rvoar-us


This email was sent to reply@reply.github.com.

If you need assistance or have questions, please contact LinkedIn Customer Service: https://www.linkedin.com/e/v2?e=0-in8rvoar-us&a=customerServiceUrl&ek=invite_guest

&copy; 2016 LinkedIn Corporation, 2029 Stierlin Court, Mountain View CA 94043. LinkedIn and the LinkedIn logo are registered trademarks of LinkedIn.

**Comment by ludoplex** [comment]
Vincent Anderson would like to connect on LinkedIn. How would you like to respond?

Accept: https://www.linkedin.com/e/v2?e=-8fg08r-injk0hap-t4&a=preRegInvite&ek=first_guest_reminder_01&li=14&m=hero&ts=accept_text&sharedKey=i4Oc8zGP&invitationID=6128513444078514177

View Vincent Anderson&#39;s profile: https://www.linkedin.com/e/v2?e=-8fg08r-injk0hap-t4&a=preRegInvite&ek=first_guest_reminder_01&li=3&m=hero&ts=profile_text&sharedKey=i4Oc8zGP&invitationID=6128513444078514177





You received an invitation to connect. LinkedIn will use your email address to make suggestions to our members in features like People You May Know. Unsubscribe here: https://www.linkedin.com/e/v2?e=-8fg08r-injk0hap-t4&t=lun&midToken=AQFmrFVhGEd36Q&ek=first_guest_reminder_01&li=16&m=unsub&ts=HTML&eid=-8fg08r-injk0hap-t4&loid=AQEtXAFDiizMqwAAAVRbBlAM84wrpUSh6GjKGLMpTa_mi6PD9dhn3f-oX2qkcNkteTb4IcbZHnzfUV7PemCQdChxmPE5edjbtfTSHVFFvjusJo-R6rlULnt9KFWNDufbS9aDh8HIZjAkaF8EnbT8Kal539nC3x6wkDlyBgI98AaOCvQBB7G-y_sM0DFWHhzM-hI6

This email was sent to reply@reply.github.com.

If you need assistance or have questions, please contact LinkedIn Customer Service: https://www.linkedin.com/e/v2?e=-8fg08r-injk0hap-t4&a=customerServiceUrl&ek=first_guest_reminder_01

&copy; 2016 LinkedIn Corporation, 2029 Stierlin Court, Mountain View CA 94043. LinkedIn and the LinkedIn logo are registered trademarks of LinkedIn.

**Comment by ludoplex** [comment]
Vincent Anderson would like to connect on LinkedIn. How would you like to respond?

Accept: https://www.linkedin.com/e/v2?e=-8fg08r-int30dv5-ah&a=preRegInvite&ek=second_guest_reminder_01&li=13&m=hero&ts=accept_text&sharedKey=i4Oc8zGP&invitationID=6128513444078514177

View Vincent Anderson&#39;s profile: https://www.linkedin.com/e/v2?e=-8fg08r-int30dv5-ah&a=preRegInvite&ek=second_guest_reminder_01&li=3&m=hero&ts=profile_text&sharedKey=i4Oc8zGP&invitationID=6128513444078514177





You received an invitation to connect. LinkedIn will use your email address to make suggestions to our members in features like People You May Know. Unsubscribe here: https://www.linkedin.com/e/v2?e=-8fg08r-int30dv5-ah&t=lun&midToken=AQFmrFVhGEd36Q&ek=second_guest_reminder_01&li=15&m=unsub&ts=HTML&eid=-8fg08r-int30dv5-ah&loid=AQEKU_gNxKMahwAAAVR9yd0qvBrh3ItgcH939XrKznyUD09e8340TbKTo5nGgIWIIjhkqbtrErboD6BTsA3ABh-rRq1432DN3jPPA3onBm0xQ1kk2-vknLdXs6O_NOTqRWix8SlDhumKBCKy8G_arEYrJnXo0QZeUl4uj58eve1ai0mo0IJkyvgbtHuA9asNK5Rv

This email was sent to reply@reply.github.com.

If you need assistance or have questions, please contact LinkedIn Customer Service: https://www.linkedin.com/e/v2?e=-8fg08r-int30dv5-ah&a=customerServiceUrl&ek=second_guest_reminder_01

&copy; 2016 LinkedIn Corporation, 2029 Stierlin Court, Mountain View CA 94043. LinkedIn and the LinkedIn logo are registered trademarks of LinkedIn.

**Pull request closed without merging**
